### PR TITLE
remove host from loadMap after remove from the ring

### PR DESCRIPTION
**Pull request by tinytub**
remove host from loadMap after remove from the ring

### CODE REVIEW

**Comment by lafikl** [comment]
Thanks for the patch!

What are you using the package for, if i may ask?

**Comment by tinytub** [comment]
A data proxy，to transfer and seprate data to several backend store. And want to find a way to balance the data flow to every backend store. This lib is simple and easy to work out these.

**Comment by lafikl** [comment]
for what organization?

**Comment by tinytub** [comment]
Sorry for the late reply,
just use in my own experimental project.

**Pull request merged**
